Name: 'Canadian Solar CS5P-220M'
BIPV: 'N'
Date: '10/5/2009'
T_NOCT: 42.4
A_c: 1.7
N_s: 96
I_sc_ref: 5.1
V_oc_ref: 59.4
I_mp_ref: 4.69
V_mp_ref: 46.9
alpha_sc: 0.004539
beta_oc: -0.22216
a_ref: 2.6373
I_L_ref: 5.114
I_o_ref: 8.196e-10
R_s: 1.065
R_sh_ref: 381.68
Adjust: 8.7
gamma_r: -0.476
Version: 'MM106'
PTC: 200.1
Technology: 'Mono-c-Si'
EgRef: 1.121
dEgdT: -0.0002677
irrad_ref: 1000
temp_ref: 25