# This file is for custom makefile variable at the project level.
# They are meant to be share by the whole project team.

APP_VERSION := 0.0.0
APPLICATION_NAME := pv_stuff
CONDA_ENVIRONMENT := pv-stuff-env
PYTHON_VERSION := 3.11