# This file is for custom makefile variable at the project level.
# They are meant to be share by the whole project team.

APP_VERSION := 0.0.0
APPLICATION_NAME := my_python_project
CONDA_ENVIRONMENT := my-python-project-env
PYTHON_VERSION := 3.11